server:
  port: 8080

spring:
  devtools:
    restart:
      exclude: logs/**

  application:
    name: shortenit

  data:
    cassandra:
      keyspace-name: shortenit
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS

  redis:
    host: redis
    port: 6379
    database: 0

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: shortenit-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all

logging:
  level:
    root: INFO
    org.springframework.data.redis: DEBUG
    org.springframework.data.cassandra.core: DEBUG
    

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: docker

  data:
    cassandra:
      contact-points: cassandra
      port: 9042
      keyspace-name: shortenit
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS

  kafka:
    bootstrap-servers: kafka:9092

  redis:
    host: redis
    port: 6379