server:
  port: 8080

spring:
  devtools:
    restart:
      exclude: logs/**

  application:
    name: url-shortener

  data:
    cassandra:
      keyspace-name: urlshortener
      contact-points: cassandra
      port: 9042
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS

  redis:
    host: redis
    port: 6379
    database: 0

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: url-shortener-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all

logging:
  level:
    root: INFO
    org.springframework.data.redis: DEBUG
